### ISSUE TITLE
Include a link to Product Hunt

### ISSUE THREAD

**Issue by jamesmills** [TreewareEarth/treeware.earth#13]
We have a page on Product Hunt (https://www.producthunt.com/posts/treeware) and it would be awesome to add a link/button/badge or something to the website.

```
<a href="https://www.producthunt.com/posts/treeware?utm_source=badge-featured&utm_medium=badge&utm_souce=badge-treeware" target="_blank"><img src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=192784&theme=light" alt="Treeware - Use the authors software, buy the author a tree. | Product Hunt" style="width: 250px; height: 54px;" width="250" height="54" /></a>
```

**Comment by jordmondson** [comment]
Hi James,

Would it be worthwhile submitting the site to https://madewithlaravel.com/ as well?

**Comment by jamesmills** [comment]
> Would it be worthwhile submitting the site to https://madewithlaravel.com/ as well?

No harm in it @jordmondson

**Comment by jamesmills** [comment]
Thank you @jordmondson
